apiVersion: v1
kind: Secret
metadata:
  name: openhiggsfield
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.olaresEnv.AUTH_SECRET | quote }}
  AUTH_USERNAME: {{ .Values.olaresEnv.AUTH_USERNAME | quote }}
  AUTH_PASSWORD: {{ .Values.olaresEnv.AUTH_PASSWORD | quote }}
  HF_API_BASE_URL: {{ .Values.olaresEnv.HF_API_BASE_URL | quote }}
  HF_API_KEY: {{ .Values.olaresEnv.HF_API_KEY | quote }}
